[package]
name = "arrays-and-strings"
version = "0.1.0"
authors = ["Seb Insua <me@sebinsua.com>"]

[[bin]]
name = "is_unique"
path = "src/is_unique.rs"

[[bin]]
name = "check_permutation"
path = "src/check_permutation.rs"
